import { relative } from "node:path";

import type { ModuleRef, RouteManifestEntry } from "../manifest.ts";
import { normalizePath } from "../router.ts";
import type { RouteTreeEntry } from "../tree.ts";

/**
 * Type generation for the virtual manifest module.
 *
 * The delivered manifest is a runtime value, so a router that derives types
 * from its route table — `@solidjs/router`'s typed `paths` proxy, say — gets
 * nothing from it: `RoutePaths` degrades to `any` as soon as the route array
 * is a plain `RouteDefinition[]` rather than a tuple. Emitting a declaration
 * that types the module as a *literal tuple* is what keeps those types alive
 * across the file-routing seam.
 *
 * Emission adapters have to preserve the tuple in turn, by mapping with a
 * `<const T extends readonly ...>` signature rather than a plain `.map`.
 */

const HEADER = `// Generated by vite-file-routes. Do not edit.
// Regenerated whenever a route file is added, changed or removed.`;

const REF_TYPES = `  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested \`pageRoutes\` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }`;

/** Extensions TypeScript can resolve through a `typeof import(...)`. */
const TYPED_MODULE = /\.([mc]?[jt]sx?)$/;

/**
 * Types a ref by the module it points at, so a page's `default` really is the
 * component and a `route` export really is the config the module declares —
 * which is what saves an emission adapter from casting either one. Modules
 * TypeScript cannot resolve (`.md`, `.mdx`) fall back to the generic ref.
 */
function refType(ref: ModuleRef, kind: "lazy" | "eager", from: string): string {
  const name = kind === "eager" ? "FileRouteEagerRef" : "FileRouteLazyRef";
  if (!TYPED_MODULE.test(ref.src)) return name;

  let specifier = normalizePath(relative(from, ref.src)).replace(TYPED_MODULE, "");
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  return `${name}<typeof import(${JSON.stringify(specifier)})>`;
}

const isLazyRefKey = (key: string) => key.startsWith("$") && !key.startsWith("$$");
const isEagerRefKey = (key: string) => key.startsWith("$$");

/**
 * Types one manifest entry, keeping `path` literal so it reaches path-derived
 * types intact. Absent refs are typed `?: undefined` rather than omitted, so
 * an adapter can read `entry.$$route` uniformly across the tuple.
 */
function entryType(
  entry: RouteManifestEntry,
  indent: string,
  nested: boolean,
  from: string
): string {
  const inner = indent + "  ";
  const fields: string[] = [`path: ${JSON.stringify(entry.path)}`];

  if (nested) fields.push(`id: ${JSON.stringify((entry as RouteTreeEntry).id)}`);
  fields.push(`page: ${entry.page ? "true" : "false"}`);

  // A convention records refs it did not emit as present-but-undefined keys,
  // so go by the value, not the key.
  const refKeys = Object.keys(entry).filter(
    key => key.startsWith("$") && entry[key] !== undefined
  );
  for (const key of refKeys) {
    const kind = isEagerRefKey(key) ? "eager" : "lazy";
    fields.push(`${key}: ${refType(entry[key] as ModuleRef, kind, from)}`);
  }
  // Reading an absent ref is how adapters branch, so keep the key present.
  if (!refKeys.some(isLazyRefKey)) fields.push(`$component?: undefined`);
  if (!refKeys.some(isEagerRefKey)) fields.push(`$$route?: undefined`);

  if (nested) {
    const children = (entry as RouteTreeEntry).children;
    fields.push(
      children?.length
        ? `children: ${tupleType(children, inner, true, from)}`
        : `children?: undefined`
    );
  }

  return `{\n${fields.map(field => `${inner}${field};`).join("\n")}\n${indent}}`;
}

function tupleType(
  entries: readonly RouteManifestEntry[],
  indent: string,
  nested: boolean,
  from: string
) {
  if (!entries.length) return "readonly []";
  const inner = indent + "  ";
  const members = entries
    .map(entry => `${inner}${entryType(entry, inner, nested, from)}`)
    .join(",\n");
  return `readonly [\n${members}\n${indent}]`;
}

/**
 * Builds the ambient declaration for `moduleId`. It is self-contained and
 * replaces `vite-file-routes/types` — reference one or the other, never
 * both, or TypeScript sees two declarations of the same module.
 */
export function serializeTypes(
  moduleId: string,
  routes: readonly RouteManifestEntry[],
  pageRoutes: readonly RouteTreeEntry[],
  /** Directory the declaration is written to; module specifiers are relative to it. */
  from: string
): string {
  return `${HEADER}

declare module ${JSON.stringify(moduleId)} {
${REF_TYPES}

  /** The flat route manifest, in scan order. */
  const routes: ${tupleType(routes, "  ", false, from)};
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: ${tupleType(pageRoutes, "  ", true, from)};
}
`;
}
